{"cveId": "CVE-2022-1011", "cwe": ["CWE-416", "CWE-416", "CWE-416", "CWE-416"], "cvss": [{"baseScore": "7.8", "version": "3.1", "Attack Vector": "Low", "Attack Complexity": "Low", "Privileges Required": "Low", "User Interaction": "None", "Scope": "Unchaged", "Confidentiality Impact": "High", "Integrity Impact": "High", "Availability Impact": "High"}], "references": ["https://git.kernel.org/pub/scm/linux/kernel/git/mszeredi/fuse.git/commit/?h=for-next", "https://bugzilla.redhat.com/show_bug.cgi?id=2064855", "https://lists.debian.org/debian-lts-announce/2022/07/msg00000.html", "https://www.debian.org/security/2022/dsa-5173", "https://www.oracle.com/security-alerts/cpujul2022.html"], "description": ["A use-after-free flaw was found in the Linux kernelâ€™s FUSE filesystem in the way a user triggers write(). This flaw allows a local user to gain unauthorized access to data from the FUSE filesystem, resulting in privilege escalation."], "published": "2022-03-18T18:15:12.177", "state": "PUBLIC", "vendorName": ["n/a"], "productName": ["kernel"], "github": {"advisories": [], "commits": [], "pocAdvisorie": null, "repo": null, "info": {}}, "pocList": ["https://github.com/xkaneiki/CVE-2022-1011", "https://github.com/xkaneiki/CVE-2022-1011"]}