{"cveId": "CVE-2019-13925", "cwe": ["CWE-400", "CWE-400", "CWE-400", "CWE-400"], "cvss": [{"baseScore": "7.5", "version": "3.1", "Attack Vector": "None", "Attack Complexity": "Low", "Privileges Required": "None", "User Interaction": "None", "Scope": "Unchaged", "Confidentiality Impact": "None", "Integrity Impact": "None", "Availability Impact": "High"}], "references": ["https://cert-portal.siemens.com/productcert/pdf/ssa-591405.pdf", "https://www.us-cert.gov/ics/advisories/icsa-20-042-10"], "description": ["A vulnerability has been identified in SCALANCE S602 (All versions >= V3.0 and < V4.1), SCALANCE S612 (All versions >= V3.0 and < V4.1), SCALANCE S623 (All versions >= V3.0 and < V4.1), SCALANCE S627-2M (All versions >= V3.0 and < V4.1). Specially crafted packets sent to port 443/tcp of affected devices could cause a Denial-of-Service condition of the web server."], "published": "2020-02-11T16:15:14.587", "state": "PUBLIC", "vendorName": ["Siemens"], "productName": ["SCALANCE S602", "SCALANCE S612", "SCALANCE S623", "SCALANCE S627-2M"], "github": {"advisories": [], "commits": [], "pocAdvisorie": null, "repo": null, "info": {}}, "pocList": []}