{"cveId": "CVE-2022-1319", "cwe": ["CWE-252", "CWE-252", "CWE-252", "CWE-252", "CWE-252"], "cvss": [{"baseScore": "7.5", "version": "3.1", "Attack Vector": "None", "Attack Complexity": "Low", "Privileges Required": "None", "User Interaction": "None", "Scope": "Unchaged", "Confidentiality Impact": "None", "Integrity Impact": "None", "Availability Impact": "High"}], "references": ["https://bugzilla.redhat.com/show_bug.cgi?id=2073890", "https://issues.redhat.com/browse/UNDERTOW-2060", "https://github.com/undertow-io/undertow/commit/1443a1a2bbb8e32e56788109d8285db250d55c8b", "https://github.com/undertow-io/undertow/commit/7c5b3ab885b5638fd3f1e8a935d5063d68aa2df3", "https://access.redhat.com/security/cve/CVE-2022-1319", "https://security.netapp.com/advisory/ntap-20221014-0006/"], "description": ["A flaw was found in Undertow. For an AJP 400 response, EAP 7 is improperly sending two response packets, and those packets have the reuse flag set even though JBoss EAP closes the connection. A failure occurs when the connection is reused after a 400 by CPING since it reads in the second SEND_HEADERS response packet instead of a CPONG."], "published": "2022-08-31T16:15:09.410", "state": "PUBLIC", "vendorName": ["n/a"], "productName": ["undertow"], "github": {"advisories": [], "commits": ["https://github.com/undertow-io/undertow/commit/1443a1a2bbb8e32e56788109d8285db250d55c8b", "https://github.com/undertow-io/undertow/commit/7c5b3ab885b5638fd3f1e8a935d5063d68aa2df3"], "pocAdvisorie": null, "repo": "https://github.com/undertow-io/undertow/", "info": {"exist": true, "topics": ["ajp", "hacktoberfest", "http", "http-server", "jakartaee", "jakartaee10", "java", "java-nio", "jboss", "servlet", "web", "websocket", "wildfly"], "langs": {"Java": 8868459, "HTML": 1782, "Shell": 86}, "avatar": "https://avatars.githubusercontent.com/u/2001898?v=4", "stargazers": 3630, "language": "Java"}}, "pocList": []}