{"cveId": "CVE-2008-4099", "cwe": ["CWE-16", "CWE-16"], "cvss": [{"baseScore": "6.4", "version": "2.0", "Attack Vector": "None", "Attack Complexity": "Low", "Privileges Required": "None", "User Interaction": "None", "Scope": "None", "Confidentiality Impact": "None", "Integrity Impact": "P", "Availability Impact": "P"}], "references": ["http://www.openwall.com/lists/oss-security/2008/09/11/1", "http://www.openwall.com/lists/oss-security/2008/09/16/4", "http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=490217", "http://packages.debian.org/changelogs/pool/main/p/python-dns/python-dns_2.3.3-1/changelog"], "description": ["PyDNS (aka python-dns) before 2.3.1-4 in Debian GNU/Linux does not use random source ports or transaction IDs for DNS requests, which makes it easier for remote attackers to spoof DNS responses, a different vulnerability than CVE-2008-1447."], "published": "2008-09-18T17:59:32.827", "state": "PUBLIC", "vendorName": ["n/a"], "productName": ["n/a"], "github": {"advisories": [], "commits": [], "pocAdvisorie": null, "repo": null, "info": {}}, "pocList": []}