{"cveId": "CVE-2022-48619", "cwe": ["CWE-755", "CWE-755"], "cvss": [{"baseScore": "5.5", "version": "3.1", "Attack Vector": "Low", "Attack Complexity": "Low", "Privileges Required": "Low", "User Interaction": "None", "Scope": "Unchaged", "Confidentiality Impact": "None", "Integrity Impact": "None", "Availability Impact": "High"}], "references": ["https://github.com/torvalds/linux/commit/409353cbe9fe48f6bc196114c442b1cff05a39bc", "https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.17.10"], "description": ["An issue was discovered in drivers/input/input.c in the Linux kernel before 5.17.10. An attacker can cause a denial of service (panic) because input_set_capability mishandles the situation in which an event code falls outside of a bitmap."], "published": "2024-01-12T03:15:08.633", "state": "PUBLIC", "vendorName": ["n/a"], "productName": ["n/a"], "github": {"advisories": [], "commits": ["https://github.com/torvalds/linux/commit/409353cbe9fe48f6bc196114c442b1cff05a39bc"], "pocAdvisorie": null, "repo": "https://github.com/torvalds/linux/", "info": {"exist": true, "topics": [], "langs": {"C": 1348363240, "Assembly": 9632676, "Shell": 5140958, "Python": 3111393, "Makefile": 2734946, "Perl": 1223890, "Rust": 1035407, "Roff": 203501, "C++": 179456, "SmPL": 166781, "Yacc": 128635, "Lex": 72476, "Awk": 71808, "Jinja": 30138, "UnrealScript": 16878, "Gherkin": 10932, "Linker Script": 9830, "M4": 3329, "Clojure": 2621, "MATLAB": 2482, "sed": 2433, "XS": 1239, "RPC": 962}, "avatar": "https://avatars.githubusercontent.com/u/1024025?v=4", "stargazers": 191042, "language": "C"}}, "pocList": []}