{"cveId": "CVE-2017-7478", "cwe": ["CWE-617", "CWE-20", "CWE-617", "CWE-20"], "cvss": [{"baseScore": "5.0", "version": "2.0", "Attack Vector": "None", "Attack Complexity": "Low", "Privileges Required": "None", "User Interaction": "None", "Scope": "None", "Confidentiality Impact": "None", "Integrity Impact": "None", "Availability Impact": "P"}], "references": ["https://www.exploit-db.com/exploits/41993/", "https://community.openvpn.net/openvpn/wiki/QuarkslabAndCryptographyEngineerAudits", "http://www.securitytracker.com/id/1038473", "http://www.securityfocus.com/bid/98444"], "description": ["OpenVPN version 2.3.12 and newer is vulnerable to unauthenticated Denial of Service of server via received large control packet. Note that this issue is fixed in 2.3.15 and 2.4.2."], "published": "2017-05-15T18:29:00.293", "state": "PUBLIC", "vendorName": ["OpenVPN Technologies, Inc"], "productName": ["openvpn"], "github": {"advisories": [], "commits": [], "pocAdvisorie": null, "repo": null, "info": {}}, "pocList": []}