{"cveId": "CVE-2021-38208", "cwe": ["CWE-476", "CWE-476"], "cvss": [{"baseScore": "5.5", "version": "3.1", "Attack Vector": "Low", "Attack Complexity": "Low", "Privileges Required": "Low", "User Interaction": "None", "Scope": "Unchaged", "Confidentiality Impact": "None", "Integrity Impact": "None", "Availability Impact": "High"}], "references": ["https://github.com/torvalds/linux/commit/4ac06a1e013cf5fdd963317ffd3b968560f33bba", "https://cdn.kernel.org/pub/linux/kernel/v5.x/ChangeLog-5.12.10", "http://www.openwall.com/lists/oss-security/2021/08/17/1", "http://www.openwall.com/lists/oss-security/2021/08/17/2", "https://bugzilla.redhat.com/show_bug.cgi?id=1992810", "http://www.openwall.com/lists/oss-security/2021/08/24/2"], "description": ["net/nfc/llcp_sock.c in the Linux kernel before 5.12.10 allows local unprivileged users to cause a denial of service (NULL pointer dereference and BUG) by making a getsockname call after a certain type of failure of a bind call."], "published": "2021-08-08T20:15:07.387", "state": "PUBLIC", "vendorName": ["n/a"], "productName": ["n/a"], "github": {"advisories": [], "commits": ["https://github.com/torvalds/linux/commit/4ac06a1e013cf5fdd963317ffd3b968560f33bba"], "pocAdvisorie": null, "repo": "https://github.com/torvalds/linux/", "info": {"exist": true, "topics": [], "langs": {"C": 1348363240, "Assembly": 9632676, "Shell": 5140958, "Python": 3111393, "Makefile": 2734946, "Perl": 1223890, "Rust": 1035407, "Roff": 203501, "C++": 179456, "SmPL": 166781, "Yacc": 128635, "Lex": 72476, "Awk": 71808, "Jinja": 30138, "UnrealScript": 16878, "Gherkin": 10932, "Linker Script": 9830, "M4": 3329, "Clojure": 2621, "MATLAB": 2482, "sed": 2433, "XS": 1239, "RPC": 962}, "avatar": "https://avatars.githubusercontent.com/u/1024025?v=4", "stargazers": 191042, "language": "C"}}, "pocList": []}