{"cveId": "CVE-2020-35530", "cwe": ["CWE-787", "CWE-787", "CWE-787", "CWE-787"], "cvss": [{"baseScore": "5.5", "version": "3.1", "Attack Vector": "Low", "Attack Complexity": "Low", "Privileges Required": "None", "User Interaction": "Required", "Scope": "Unchaged", "Confidentiality Impact": "None", "Integrity Impact": "None", "Availability Impact": "High"}], "references": ["https://github.com/LibRaw/LibRaw/issues/272", "https://github.com/LibRaw/LibRaw/commit/11c4db253ef2c9bb44247b578f5caa57c66a1eeb", "https://lists.debian.org/debian-lts-announce/2022/09/msg00024.html"], "description": ["In LibRaw, there is an out-of-bounds write vulnerability within the \"new_node()\" function (libraw\\src\\x3f\\x3f_utils_patched.cpp) that can be triggered via a crafted X3F file."], "published": "2022-09-01T18:15:08.770", "state": "PUBLIC", "vendorName": ["n/a"], "productName": ["LibRaw"], "github": {"advisories": [], "commits": ["https://github.com/LibRaw/LibRaw/commit/11c4db253ef2c9bb44247b578f5caa57c66a1eeb"], "pocAdvisorie": null, "repo": "https://github.com/LibRaw/LibRaw/", "info": {"exist": true, "topics": [], "langs": {"C++": 2039664, "C": 19129, "M4": 8267, "QMake": 6279, "Makefile": 5359, "Shell": 1869, "Perl": 1289}, "avatar": "https://avatars.githubusercontent.com/u/435672?v=4", "stargazers": 1217, "language": "C++"}}, "pocList": []}