{"cveId": "CVE-2021-30499", "cwe": ["CWE-119", "CWE-119", "CWE-787", "CWE-119", "CWE-787"], "cvss": [{"baseScore": "7.8", "version": "3.1", "Attack Vector": "Low", "Attack Complexity": "Low", "Privileges Required": "None", "User Interaction": "Required", "Scope": "Unchaged", "Confidentiality Impact": "High", "Integrity Impact": "High", "Availability Impact": "High"}], "references": ["https://bugzilla.redhat.com/show_bug.cgi?id=1948679", "https://github.com/cacalabs/libcaca/issues/54", "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/6WFGYICNTMNDNMDDUV4G2RYFB5HNJCOV/", "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/PC7EGOEQ5C4OD66ZUJJIIYEXBTZOCMZX/", "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/ZSBCRN6EGQJUVOSD4OEEQ6XORHEM2CUL/", "https://lists.debian.org/debian-lts-announce/2024/04/msg00004.html"], "description": ["A flaw was found in libcaca. A buffer overflow of export.c in function export_troff might lead to memory corruption and other potential consequences."], "published": "2021-05-27T00:15:08.440", "state": "PUBLIC", "vendorName": ["n/a"], "productName": ["libcaca"], "github": {"advisories": [], "commits": [], "pocAdvisorie": null, "repo": null, "info": {}}, "pocList": []}