{"cveId": "CVE-2020-13353", "cwe": ["CWE-613", "CWE-613"], "cvss": [{"baseScore": "2.5", "version": "3.1", "Attack Vector": "Low", "Attack Complexity": "High", "Privileges Required": "High", "User Interaction": "None", "Scope": "Complete", "Confidentiality Impact": "Low", "Integrity Impact": "None", "Availability Impact": "None"}], "references": ["https://gitlab.com/gitlab-org/gitaly/-/issues/2882", "https://gitlab.com/gitlab-org/cves/-/blob/master/2020/CVE-2020-13353.json"], "description": ["When importing repos via URL, one time use git credentials were persisted beyond the expected time window in Gitaly 1.79.0 or above."], "published": "2020-11-17T01:15:13.310", "state": "PUBLIC", "vendorName": ["GitLab"], "productName": ["Gitaly"], "github": {"advisories": [], "commits": [], "pocAdvisorie": null, "repo": null, "info": {}}, "pocList": []}