{"cveId": "CVE-2020-1735", "cwe": ["CWE-22", "CWE-22", "CWE-22", "CWE-22"], "cvss": [{"baseScore": "4.2", "version": "3.1", "Attack Vector": "Low", "Attack Complexity": "Low", "Privileges Required": "High", "User Interaction": "Required", "Scope": "Complete", "Confidentiality Impact": "Low", "Integrity Impact": "Low", "Availability Impact": "None"}], "references": ["https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2020-1735", "https://github.com/ansible/ansible/issues/67793", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/WQVOQD4VAIXXTVQAJKTN7NUGTJFE2PCB/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/DKPA4KC3OJSUFASUYMG66HKJE7ADNGFW/", "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/MRRYUU5ZBLPBXCYG6CFP35D64NP2UB2S/", "https://security.gentoo.org/glsa/202006-11", "https://www.debian.org/security/2021/dsa-4950"], "description": ["A flaw was found in the Ansible Engine when the fetch module is used. An attacker could intercept the module, inject a new path, and then choose a new destination path on the controller node. All versions in 2.7.x, 2.8.x and 2.9.x branches are believed to be vulnerable."], "published": "2020-03-16T16:15:13.890", "state": "PUBLIC", "vendorName": ["Red Hat"], "productName": ["ansible"], "github": {"advisories": [], "commits": [], "pocAdvisorie": null, "repo": null, "info": {}}, "pocList": []}