{"cveId": "CVE-2022-24309", "cwe": ["CWE-284", "CWE-284", "CWE-284"], "cvss": [{"baseScore": "6.8", "version": "3.1", "Attack Vector": "None", "Attack Complexity": "High", "Privileges Required": "Low", "User Interaction": "None", "Scope": "Unchaged", "Confidentiality Impact": "High", "Integrity Impact": "High", "Availability Impact": "None"}], "references": ["https://cert-portal.siemens.com/productcert/pdf/ssa-148641.pdf", "https://cert-portal.siemens.com/productcert/html/ssa-148641.html"], "description": ["A vulnerability has been identified in Mendix Runtime V7 (All versions < V7.23.29), Mendix Runtime V8 (All versions < V8.18.16), Mendix Runtime V9 (All versions < V9.13 only with Runtime Custom Setting *DataStorage.UseNewQueryHandler* set to False). If an entity has an association readable by the user, then in some cases, Mendix Runtime may not apply checks for XPath constraints that parse said associations, within apps running on affected versions. A malicious user could use this to dump and manipulate sensitive data."], "published": "2022-03-08T12:15:11.580", "state": "PUBLIC", "vendorName": ["Siemens"], "productName": ["Mendix Runtime V7", "Mendix Runtime V8", "Mendix Runtime V9"], "github": {"advisories": [], "commits": [], "pocAdvisorie": null, "repo": null, "info": {}}, "pocList": []}