{"cveId": "CVE-2022-0845", "cwe": ["CWE-94", "CWE-94", "CWE-94", "CWE-94"], "cvss": [{"baseScore": "9.8", "version": "3.1", "Attack Vector": "None", "Attack Complexity": "Low", "Privileges Required": "None", "User Interaction": "None", "Scope": "Unchaged", "Confidentiality Impact": "High", "Integrity Impact": "High", "Availability Impact": "High"}], "references": ["https://huntr.dev/bounties/a795bf93-c91e-4c79-aae8-f7d8bda92e2a", "https://github.com/pytorchlightning/pytorch-lightning/commit/8b7a12c52e52a06408e9231647839ddb4665e8ae"], "description": ["Code Injection in GitHub repository pytorchlightning/pytorch-lightning prior to 1.6.0."], "published": "2022-03-05T22:15:07.843", "state": "PUBLIC", "vendorName": ["pytorchlightning"], "productName": ["pytorchlightning/pytorch-lightning"], "github": {"advisories": [], "commits": ["https://github.com/pytorchlightning/pytorch-lightning/commit/8b7a12c52e52a06408e9231647839ddb4665e8ae"], "pocAdvisorie": null, "repo": "https://github.com/pytorchlightning/pytorch-lightning/", "info": {"exist": true, "topics": ["ai", "artificial-intelligence", "data-science", "deep-learning", "machine-learning", "python", "pytorch"], "langs": {"Python": 4745269, "Shell": 10985, "Dockerfile": 10759, "Makefile": 1822}, "avatar": "https://avatars.githubusercontent.com/u/58386951?v=4", "stargazers": 29245, "language": "Python"}}, "pocList": []}