{"cveId": "CVE-2024-35805", "cwe": [], "cvss": [], "references": ["https://git.kernel.org/stable/c/e7d4cff57c3c43fdd72342c78d4138f509c7416e", "https://git.kernel.org/stable/c/9759ff196e7d248bcf8386a7451d6ff8537a7d9c", "https://git.kernel.org/stable/c/116562e804ffc9dc600adab6326dde31d72262c7", "https://git.kernel.org/stable/c/3d47eb405781cc5127deca9a14e24b27696087a1", "https://git.kernel.org/stable/c/e50f83061ac250f90710757a3e51b70a200835e2", "https://git.kernel.org/stable/c/fa5c055800a7fd49a36bbb52593aca4ea986a366", "https://git.kernel.org/stable/c/5f4ad4d0b0943296287313db60b3f84df4aad683", "https://git.kernel.org/stable/c/6e7132ed3c07bd8a6ce3db4bb307ef2852b322dc"], "description": ["In the Linux kernel, the following vulnerability has been resolved:\n\ndm snapshot: fix lockup in dm_exception_table_exit\n\nThere was reported lockup when we exit a snapshot with many exceptions.\nFix this by adding \"cond_resched\" to the loop that frees the exceptions."], "published": "2024-05-17T14:15:13.793", "state": "PUBLIC", "vendorName": ["Linux"], "productName": ["Linux"], "github": {"advisories": [], "commits": [], "pocAdvisorie": null, "repo": null, "info": {}}, "pocList": []}