{"cveId": "CVE-2011-4944", "cwe": ["CWE-264", "CWE-264"], "cvss": [{"baseScore": "1.9", "version": "2.0", "Attack Vector": "Low", "Attack Complexity": "M", "Privileges Required": "None", "User Interaction": "None", "Scope": "None", "Confidentiality Impact": "Partial", "Integrity Impact": "None", "Availability Impact": "None"}], "references": ["http://secunia.com/advisories/50858", "http://secunia.com/advisories/51024", "http://secunia.com/advisories/51040", "http://secunia.com/advisories/51087", "http://www.ubuntu.com/usn/USN-1596-1", "http://www.ubuntu.com/usn/USN-1613-1", "http://www.ubuntu.com/usn/USN-1613-2", "http://www.ubuntu.com/usn/USN-1616-1", "http://lists.apple.com/archives/security-announce/2013/Oct/msg00004.html", "http://www.ubuntu.com/usn/USN-1592-1", "http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=650555", "http://bugs.python.org/file23824/pypirc-secure.diff", "http://bugs.python.org/issue13512", "http://lists.opensuse.org/opensuse-security-announce/2020-01/msg00040.html", "http://secunia.com/advisories/51089", "http://www.openwall.com/lists/oss-security/2012/03/27/10", "http://www.openwall.com/lists/oss-security/2012/03/27/2", "http://www.openwall.com/lists/oss-security/2012/03/27/5", "http://www.ubuntu.com/usn/USN-1615-1", "https://bugzilla.redhat.com/show_bug.cgi?id=758905"], "description": ["Python 2.6 through 3.2 creates ~/.pypirc with world-readable permissions before changing them after data has been written, which introduces a race condition that allows local users to obtain a username and password by reading this file."], "published": "2012-08-27T23:55:01.290", "state": "PUBLIC", "vendorName": ["n/a"], "productName": ["n/a"], "github": {"advisories": [], "commits": [], "pocAdvisorie": null, "repo": null, "info": {}}, "pocList": []}